name: Resuable workflow

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
        description: Target environment for the build
    secrets:
      CLIENT_ID:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:
      # Install node
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code from repo
        uses: actions/checkout@v3

      - name: install @actions/core package
        run: npm i @actions/core

      - name: Prepare Tag
        id: prepare-tag
        uses: './.github/workflows/actions/setup-tag'
        with:
          tag: ${{ vars.TAG_VERSION }}

      - name: Config git globals
        run: |
          git config --global user.name "$(git log -n 1 --pretty=format:%an)"
          git config --global user.email "$(git log -n 1 --pretty=format:%ae)"


      - name: Create Tag
        env: 
          tag: ${{ steps.prepare-tag.outputs.tag-version }}
        run: |
          git tag -a $tag -m "Tag ${{ env.tag }} for ${{ inputs.target }}"
          git push origin $tag


      - name: Create Release
        env:
          tag: ${{ steps.prepare-tag.outputs.tag-version }}
        run: |
          gh release create "$tag" \
          --repo "$GITHUB_REPOSITORY" \
          --title "${GITHUB_REPOSITORY#*/} ${tag#v}" \
          --generate-notes
          --verify-tag
          --notes-from-tag
          --prerelease
        
      - shell: bash
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: npm run build

      - name: Persiste tag version
        run: |
          gh variable set TAG_VERSION \
          --body ${{ steps.prepare-tag.outputs.tag-version }}
          --env ${{ inputs.target }}
          --org ${{ github.repository_owner }}