name: Resuable workflow

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
        description: Target environment for the build
    secrets:
      CLIENT_ID:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:
      # Install node
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1

      - name: Config git globals
        run: |
          git config --global user.name "$(git log -n 1 --pretty=format:%an)"
          git config --global user.email "$(git log -n 1 --pretty=format:%ae)"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code from repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-tags: true


      - name: Get Tag
        id: get-tag
        shell: bash
        run: |
          search=$(echo "${{ inputs.target }}" | cut -c 1)
          default_tag="${search}0.0.0"
          version=$(git describe --tags --always $(git rev-list --tags --max-count=1) | grep ^$search)
          echo "current_tag=${version:-$default_tag}" >> $GITHUB_ENV

      - name: install @actions/core package
        run: npm i @actions/core

      - name: Prepare Tag
        id: prepare-tag
        uses: './.github/workflows/actions/setup-tag'
        with:
          tag: ${{ env.current_tag }}


      - name: Create Tag
        env: 
          tag: ${{ steps.prepare-tag.outputs.tag-version }}
        run: |
          git tag -a $tag -m "Tag ${{ env.tag }} for ${{ inputs.target }}"
          git push origin $tag


      - name: Create Release
        env:
          tag: ${{ steps.prepare-tag.outputs.tag-version }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "$tag" \
          --repo "$GITHUB_REPOSITORY" \
          --title "${GITHUB_REPOSITORY#*/} ${tag#v}" \
          --generate-notes \
          --verify-tag \
          --prerelease
        
      - name: Triggering build
        shell: bash
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: npm run build -- $CLIENT_ID

      - name: Persist tag version
        env: 
          tag: ${{ steps.prepare-tag.outputs.tag-version }}
        run: |
          sed -i "s/${{ inputs.target }}=/${{ inputs.target }}=$tag/g" ../../version.ini