name: Resuable workflow

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      tag-version:
        required: true
        type: string
    secrets:
      CLIENT_ID:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:
      # Install node
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code from repo
        uses: actions/checkout@v3

      - name: Create Tag 
        if: inputs.target == 'development'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ inputs.tag-version }}',
              sha: context.sha
            })
        
      - shell: bash
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: npm run build