name: Resuable workflow

on:
    workflow_call:
        secrets:
            client-id: 
                required: true
        inputs:
            target:
                required: true
                type: string

jobs:
    build:
        if: inputs.target != 'production' || inputs
        runs-on: ubuntu-latest
        environment: ${{ inputs.target }}
        steps:
            # Install node
            - name: Setup Node.js environment
              uses: actions/setup-node@v3.8.1
      
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout code from repo
              uses: actions/checkout@v3
      
            - name: Create Tag 
              uses: actions/github-script@v6
              with:
                script: |
                  github.rest.git.createRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: 'refs/tags/<tagname>',
                    sha: context.sha
                  })
              
            - shell: bash
              env:
                CLIENT_ID: ${{ secrets.CLIENT_ID }}
              run: npm run build