name: test workflow

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps:
      - name: checking readiness
        id: check
        env:
          isProduction: true
          isStaging: true
          isDevelopment: true
        run: |
          check=$isProduction || $isStaging || $isDevelopment
          JSON_STRING=$(node -pe "
            JSON.stringify({
              isProduction: '$isProduction',
              isStaging: '$isStaging',
              isDevelopment: '$isDevelopment',
              check: $check
            });
          ")
          echo "::set-output name=result::$JSON_STRING"